requires 'perl', '5.040001';
requires 'Crypt::Age', '0.004';
requires 'Crypt::PBKDF2';
requires 'CryptX', '0.091';
requires 'File::ShareDir';
requires 'File::SOPS', '0.004';
requires 'IO::Async';
requires 'IO::K8s', '1.108';
requires 'IPC::Run';
requires 'JSON::MaybeXS';
requires 'Kubernetes::REST', '1.108';
requires 'LWP::Protocol::https';
requires 'Moo';
requires 'MooX::Cmd', '1.000';
requires 'MooX::Options', '4.103';
requires 'MooX::Singleton';
requires 'namespace::clean';
requires 'Net::Async::Kubernetes', '0.008';
requires 'Path::Tiny';
requires 'Rex';
requires 'Rex::LibSSH', '0.004';
requires 'Term::ReadKey';
requires 'Try::Tiny';
requires 'WWW::Hetzner', '0.101';
requires 'YAML::XS';
