---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-system

resources:
- ../../

images:
- name: raudssus/ocp
  newName: REGISTRY_HOST_PLACEHOLDER/ocp
  newTag: dev

patches:
- target:
    kind: Deployment
    name: robocop
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
